script: "runghc -isrc -itests tests/CountVonCount/TestSuite.hs --plain"
before_install:
    - "cd count-von-count"
    - "sudo add-apt-repository ppa:gspreemann/haskell"
    - "sudo apt-get update"
    - "sudo apt-get install -y ghc cabal-install"
    - "cabal update"
    - "cabal install"
    - "cabal install test-framework-hunit"
notifications:
  email: false
  irc:
    - "wina.ugent.be#zeus"
